"""Offline introductory lessons for the curated topic catalog."""
from .topic_catalog import TOPICS

# Definition, mechanism, example, takeaway; aligned with the curated catalog.
LESSONS = [
    ("Python executes instructions to manipulate values and produce results.", "CPython compiles source into bytecode, then executes it in its interpreter.", "x = 2 + 3 stores 5. print(x) displays 5.", "Execution can fail with a syntax error before running, or a runtime exception later."),
    ("A list is an ordered, mutable collection of items.", "Access items by zero-based position; append adds an item at the end.", "colors = ['red', 'blue']; colors[0] returns 'red'.", "Use lists when order matters or you need to add and remove items."),
    ("A dictionary maps unique, hashable keys to values.", "A hash table locates a key without scanning every entry in typical cases.", "person = {'name': 'Alice', 'age': 25}; person['name'] returns 'Alice'.", "Lookup is average O(1), not guaranteed constant time in every case."),
    ("A function packages a reusable task behind a name.", "Parameters accept inputs; a return statement sends a result back to the caller.", "def double(x): return x * 2; calling double(4) returns 8.", "Keep each function focused on one task so it is easier to test and reuse."),
    ("API means Application Programming Interface: a defined way for software components to interact.", "For a web API, a client sends a request to an endpoint. The server processes it and returns a response.", "A weather app sends GET /weather?city=Delhi. Example response: {\"temperature_c\": 28}. The app displays 28 C.", "APIs are contracts. Check required inputs, authentication, status codes and usage limits. Not every API uses HTTP."),
    ("Debugging is finding and correcting the cause of unexpected program behavior.", "Reproduce the issue, inspect values and trace execution to narrow down the cause.", "If a total is wrong, print each input or pause at a breakpoint before the calculation.", "Fix the cause and test the failing case again; avoid changing many things at once."),
    ("Version control records changes so you can inspect and recover earlier work.", "Git stores commits; branches let you develop changes separately before merging.", "Create a branch, edit a file, review the diff, then commit the change.", "Commit focused changes and keep passwords and API keys out of the repository."),
    ("A database index is an extra structure that helps locate rows efficiently.", "The database can search indexed values instead of scanning every row for suitable queries.", "An index on customer_id can speed up finding orders for one customer.", "Indexes use storage and add write overhead; choose them for real query patterns."),
    ("Machine learning fits patterns from examples to make predictions on new inputs.", "Training adjusts model parameters to reduce prediction errors on training examples.", "A spam classifier learns from messages labeled spam or not spam.", "Evaluate on unseen data: memorizing training examples is not the same as learning useful patterns."),
    ("Training data fits the model. Test data measures its performance on unseen examples.", "Keep test data separate; use validation data for model choices and tuning.", "Train on earlier customer records and test on a held-out set that reflects real use.", "Data leakage makes test scores look better than real-world performance."),
    ("Overfitting happens when a model learns training details that do not generalize.", "A model may fit noise as well as useful patterns, creating a gap between training and validation results.", "A very deep tree can memorize examples yet misclassify new ones.", "Use validation, simpler models, regularization or more representative data."),
    ("A feature is an input variable used to describe an example for a model.", "Raw information is selected or transformed into values the model can use.", "For a house-price model, features might include floor area and number of bedrooms.", "Use features available at prediction time; avoid leaking the answer into the inputs."),
    ("Classification predicts categories; regression predicts numerical quantities.", "The target you want to predict determines which task you are solving.", "Spam or not spam is classification. Predicting a delivery time is regression.", "Choose evaluation metrics suited to the target and the cost of mistakes."),
    ("Accuracy is the fraction of predictions that are correct.", "Divide correct predictions by all predictions; compare against a simple baseline.", "If 99 of 100 cases are negative, always predicting negative gives 99% accuracy.", "For imbalanced classes, also examine precision, recall and the confusion matrix."),
    ("A confusion matrix counts actual classes against predicted classes.", "For a binary task it separates true positives, true negatives, false positives and false negatives.", "A spam filter may wrongly block a real message: that is a false positive for spam.", "Use the matrix to see which mistakes happen, not just how many predictions are correct."),
    ("A recommendation system ranks items a person may find useful.", "It can use item similarity, user interactions or a combination of both.", "A movie service suggests films similar to ones you watched and enjoyed.", "Clicks are imperfect signals; new users, privacy and narrow recommendations need care."),
    ("A neural-network neuron transforms numerical inputs into an output.", "It combines inputs with weights and a bias, then applies an activation function.", "Two input features can contribute differently because their learned weights differ.", "It is a mathematical unit inspired by biology, not a complete model of a brain cell."),
    ("An embedding represents an item as a vector of numbers.", "Training arranges vectors so relevant relationships can be captured by distances or similarities.", "A search system compares a question vector with document vectors to find related passages.", "Similarity depends on the model and task; nearby vectors do not prove factual equivalence."),
    ("A language model uses context to predict and generate sequences of tokens.", "It processes your prompt and repeatedly selects a next token based on learned patterns.", "Given a request to summarize a paragraph, it generates a shorter response token by token.", "Fluent output is not proof of accuracy; check important claims against reliable information."),
    ("A hallucination is generated content that is unsupported or incorrect.", "A model can produce plausible wording even when relevant facts are missing or uncertain.", "It may invent a book title or cite a paper that does not exist.", "Verify claims and sources; retrieved context can help but does not eliminate errors."),
    ("Prompt engineering means specifying the task and context clearly.", "Describe the goal, audience, constraints and desired output, then evaluate the result.", "Instead of 'Explain lists', ask 'Explain Python lists to a beginner with one runnable example'.", "Clear prompts help, but they cannot guarantee correctness or create missing knowledge."),
    ("Retrieval augmented generation supplies retrieved information to a language model.", "Search documents, select relevant passages, then ask the model to answer using that context.", "A support assistant retrieves a product manual before answering a setup question.", "Retrieval quality matters; check whether cited passages actually support the answer."),
    ("Private data includes information that should not be shared with unauthorized people or services.", "Minimize inputs, remove identifiers and secrets, and use approved access controls.", "Replace a customer's name and account number with placeholders before drafting an example.", "Review the service's data handling and your organization's rules before sending sensitive content."),
    ("Data cleaning corrects inconsistencies that interfere with analysis.", "Inspect missing values, duplicates, formats and implausible values before choosing corrections.", "Convert dates to one format and identify repeated customer rows.", "Keep the original data and document changes; unusual values are not automatically errors."),
    ("Charts turn data into visual patterns that are easier to compare.", "Choose a chart for the question: bars compare categories; lines show change over time.", "A monthly sales line chart can reveal seasonal peaks and unexpected drops.", "Label axes and units clearly; scales and missing context can mislead readers."),
    ("Correlation means variables vary together; causation means one influences another.", "A third factor, reverse direction or chance may explain an observed association.", "Ice-cream sales and swimming both rise in warm weather; one need not cause the other.", "Causal claims need a suitable study design and justified assumptions."),
    ("A CSV file stores tabular text as rows with separated fields.", "Python's csv module reads fields while handling delimiters and quoted values.", "Read a sales CSV with csv.DictReader, convert amount strings to numbers, then sum them.", "Check encoding, headers and missing values; a CSV does not define data types by itself."),
    ("Automation uses software to perform repeatable steps.", "Define inputs and rules, run the task, check results and record failures.", "A script renames downloaded reports and moves them into dated folders.", "Start with a small, reversible task and keep human review for important decisions."),
    ("Big O describes how resource use grows with input size.", "It focuses on growth rather than exact time on a specific computer.", "Scanning n items is O(n). A typical nested scan over all pairs is O(n squared).", "Constants, input patterns and hardware still affect actual performance."),
    ("A small project turns one clear problem into a working solution.", "Define a minimal result, implement one path, test it and improve from feedback.", "Build a command-line expense tracker that first adds entries and prints a total.", "Finish a useful small version before adding accounts, dashboards or complex integrations."),
]


def lesson_for(topic):
    for title, lesson in zip(TOPICS, LESSONS):
        if title.casefold() == topic.casefold():
            return lesson
    aliases = {"python dictionaries": 2, "python dictionary": 2, "api": 4}
    index = aliases.get(topic.casefold().strip())
    return LESSONS[index] if index is not None else None
